var code="",icon=0,isrunning=!1;
chrome.tabs.onUpdated.addListener(function(){chrome.tabs.query({active:!0},function(a){for(var e=0;e<a.length;e++){var d=a[e].url,b=d.toLowerCase();void 0===d&&(b="http://www.example.com");-1!==b.search("quizlet.com/")&&0!==b.search("quizlet.com/")?-1!==b.search("match")&&0!==b.search("match")?!1===isrunning&&(chrome.browserAction.setIcon({path:"icon.png"}),e=a.length):-1!==b.search("space")&&0!==b.search("space")?!1===isrunning&&(e=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==b.search("/learn")&&
0!==b.search("/learn")?!1===isrunning&&(e=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==b.search("/gravity")&&0!==b.search("/gravity")?!1===isrunning&&(e=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==b.search("/test")&&0!==b.search("/test")?!1===isrunning&&(e=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==b.search("/spell")&&0!==b.search("/spell")?!1===isrunning&&(e=a.length,chrome.browserAction.setIcon({path:"icon.png"})):(chrome.browserAction.setIcon({path:"icon_disable.png"}),
isrunning=!1):(chrome.browserAction.setIcon({path:"icon_disable.png"}),isrunning=!1)}})});
chrome.tabs.onActivated.addListener(function(a){chrome.tabs.query({active:!0},function(a){for(var d=0;d<a.length;d++){var b=a[d].url,c=b.toLowerCase();void 0===b&&(c="http://www.example.com");-1!==c.search("quizlet.com/")&&0!==c.search("quizlet.com/")?-1!==c.search("match")&&0!==c.search("match")?!1===isrunning&&(chrome.browserAction.setIcon({path:"icon.png"}),d=a.length):-1!==c.search("space")&&0!==c.search("space")?!1===isrunning&&(chrome.browserAction.setIcon({path:"icon.png"}),d=a.length):-1!==
c.search("/learn")&&0!==c.search("/learn")?!1===isrunning&&(d=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==c.search("/gravity")&&0!==c.search("/gravity")?!1===isrunning&&(d=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==c.search("/test")&&0!==c.search("/test")?!1===isrunning&&(d=a.length,chrome.browserAction.setIcon({path:"icon.png"})):-1!==c.search("/spell")&&0!==c.search("/spell")?!1===isrunning&&(d=a.length,chrome.browserAction.setIcon({path:"icon.png"})):chrome.browserAction.setIcon({path:"icon_disable.png"}):
chrome.browserAction.setIcon({path:"icon_disable.png"})}})});
chrome.browserAction.onClicked.addListener(function(a){a=a.url.toLowerCase();-1!==a.search("quizlet.com/")&&0!==a.search("quizlet.com/")?-1!==a.search("match")&&0!==a.search("match")?(code=-1!==a.search("micromatch")&&0!==a.search("micromatch")?"microscatter.js":"Scatter.js",chrome.browserAction.setIcon({path:"icon_active.png"}),isrunning=!0,setTimeout(function(){chrome.browserAction.setIcon({path:"icon.png"});isrunning=!1},1E3)):-1!==a.search("space")&&0!==a.search("space")?(code="space.js",chrome.browserAction.setIcon({path:"icon_active.png"}),
isrunning=!0,setTimeout(function(){chrome.browserAction.setIcon({path:"icon.png"});isrunning=!1},1E3)):-1!==a.search("/learn")&&0!==a.search("/learn")?(code="Learn.js",chrome.browserAction.setIcon({path:"icon_active.png"}),isrunning=!0,setTimeout(function(){chrome.browserAction.setIcon({path:"icon.png"});isrunning=!1},1E3)):-1!==a.search("/gravity")&&0!==a.search("/gravity")?(code="Gravity.js",chrome.browserAction.setIcon({path:"icon_active.png"}),isrunning=!0,setTimeout(function(){chrome.browserAction.setIcon({path:"icon.png"});
isrunning=!1},1E3)):-1!==a.search("/test")&&0!==a.search("/test")?(code="test.js",chrome.browserAction.setIcon({path:"icon_active.png"}),isrunning=!0,setTimeout(function(){chrome.browserAction.setIcon({path:"icon.png"});isrunning=!1},1E3)):-1!==a.search("/spell")&&0!==a.search("/spell")?(code="spell.js",chrome.browserAction.setIcon({path:"icon_active.png"}),isrunning=!0,setTimeout(function(){chrome.browserAction.setIcon({path:"icon.png"});isrunning=!1},1E3)):(code="",isrunning=!1):(code="",isrunning=
!1);chrome.tabs.executeScript({file:code,matchAboutBlank:!0})});